### ISSUE TITLE
Parallel processing crashes on my system

### ISSUE THREAD

**Issue by kramlie** [brummer10/guitarix.vst#30]
The latest commit as of today (https://github.com/brummer10/guitarix.vst/commit/1904d720383b0859effcb8669aec4dcefed3e844) crashes when I load my existing project.

This is the backtrace:

```
#0  0x00007fff5bbfee13 in gx_engine::MonoModuleChain::process(int, float*, float*) (this=0x9a000258, count=7143541, input=0xa003e0073006e, output=0xa003e0073006e)
    at ../../guitarix/trunk/src/gx_head/engine/gx_engine_audio.cpp:351
#1  0x00007fff5bd93b31 in gx_jack::GxJack::process_mono(unsigned int, float*, float*) (this=0x9a06e880, nframes=7143541, input_buffer=0xa003e0073006e, output_buffer=0xa003e0073006e)
    at ../../guitarix/trunk/src/gx_head/engine/gx_jack_wrapper.cpp:135
#2  0x00007fff5bbe65dd in GuitarixProcessor::processParallel() (this=0x6a4a3c60) at ../../Source/GuitarixProcessor.cpp:1086
#3  0x00007fff5bbef163 in ProcessPtr::wrap<GuitarixProcessor, &GuitarixProcessor::processParallel>(void*) (instance=0x6a4a3c60) at ../../Source/ParallelThread.h:118
#4  0x00007fff5bbe88fb in ProcessPtr::process() const (this=0x6a4a3eb8) at ../../Source/ParallelThread.h:109
#5  0x00007fff5bbe8fd5 in ParallelThread::run()::{lambda()#1}::operator()() const (__closure=0x9c52b728) at ../../Source/ParallelThread.h:302
#6  0x00007fff5bbf6e12 in std::__invoke_impl<void, ParallelThread::run()::{lambda()#1}>(std::__invoke_other, ParallelThread::run()::{lambda()#1}&&) (__f=...) at /usr/include/c++/9/bits/invoke.h:60
#7  0x00007fff5bbf6dbb in std::__invoke<ParallelThread::run()::{lambda()#1}>(std::__invoke_result&&, (ParallelThread::run()::{lambda()#1}&&)...) (__fn=...) at /usr/include/c++/9/bits/invoke.h:95
#8  0x00007fff5bbf6d5c in std::thread::_Invoker<std::tuple<ParallelThread::run()::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x9c52b728) at /usr/include/c++/9/thread:244
#9  0x00007fff5bbf6d2e in std::thread::_Invoker<std::tuple<ParallelThread::run()::{lambda()#1}> >::operator()() (this=0x9c52b728) at /usr/include/c++/9/thread:251
#10 0x00007fff5bbf6d0e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<ParallelThread::run()::{lambda()#1}> > >::_M_run() (this=0x9c52b720) at /usr/include/c++/9/thread:195
#11 0x00007ffff7c0cdf4 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007ffff7d32609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#13 0x00007ffff78cd353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Is that enough, or do you need a more elaborate test case?

Reverting to the previous commit fixes the problem.

**Comment by brummer10** [comment]
Did your project using the stereo input mode or the mono input? Or happen that in both cases?
Are you in the audio/ realtime group and allowed to set higher priority's (RT)

**Comment by brummer10** [comment]
Unfortunately I can't reproduce this issue, but I've tried a small modification which may solve it?

**Comment by kramlie** [comment]
That did the trick! Thanks @brummer10!
